modLoader="javafml"
loaderVersion="[46,)"
license="MIT"

[[mods]]
    issueTrackerURL="https://github.com/BlakeBr0/MysticalAgriculture/issues"
    modId="mysticalcustomization"
    version="${file.jarVersion}"
    displayName="Mystical Customization"
    # updateJSONURL="http://myurl.me/"
    displayURL="https://blakesmods.com/mystical-customization"
    # logoFile="examplemod.png"
    credits=""
    authors="BlakeBr0"
    description='''
    Allows modpack creators to add new content and modify existing content in Mystical Agriculture.
    '''

    [[dependencies.mysticalcustomization]]
        modId="forge"
        mandatory=true
        versionRange="[46.0.0,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.mysticalcustomization]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.20,1.20.1]"
        ordering="NONE"
        side="BOTH"
    [[dependencies.mysticalcustomization]]
        modId="cucumber"
        mandatory=true
        versionRange="[6.1.0,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.mysticalcustomization]]
        modId="mysticalagriculture"
        mandatory=true
        versionRange="[7.0.0,)"
        ordering="NONE"
        side="BOTH"
