modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
    issueTrackerURL="https://github.com/BlakeBr0/MysticalAgriculture/issues"
    modId="mysticalcustomization"
    version="${file.jarVersion}"
    displayName="Mystical Customization"
    # updateJSONURL="http://myurl.me/"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/mystical-customization"
    # logoFile="examplemod.png"
    credits="BlakeBr0"
    authors="BlakeBr0"
    description='''
    Allows modpack creators to add new content and modify existing content in Mystical Agriculture.
    '''

    [[dependencies.mysticalcustomization]]
        modId="forge"
        mandatory=true
        versionRange="[40.0,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.mysticalcustomization]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.18.2,1.19)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.mysticalcustomization]]
        modId="cucumber"
        mandatory=true
        versionRange="[5.1.0,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.mysticalcustomization]]
        modId="mysticalagriculture"
        mandatory=true
        versionRange="[5.0.3,)"
        ordering="NONE"
        side="BOTH"
