license="MIT"

[[mods]]
    issueTrackerURL="https://github.com/BlakeBr0/MysticalCustomization/issues"
    modId="mysticalcustomization"
    version="${mod_version}"
    displayName="Mystical Customization"
    updateJSONURL="https://api.blakesmods.com/v2/mods/mysticalcustomization/26.1/updates"
    displayURL="https://blakesmods.com/mystical-customization"
    # logoFile="examplemod.png"
    credits=""
    authors="BlakeBr0"
    description='''
    Allows modpack creators to add new content and modify existing content in Mystical Agriculture.
    '''

    [[dependencies.mysticalcustomization]]
        modId="neoforge"
        mandatory=true
        versionRange="[26.1.2.41-beta,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.mysticalcustomization]]
        modId="minecraft"
        mandatory=true
        versionRange="[26.1.2,26.2)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.mysticalcustomization]]
        modId="cucumber"
        mandatory=true
        versionRange="[${cucumber_version},)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.mysticalcustomization]]
        modId="mysticalagriculture"
        mandatory=true
        versionRange="[${mysticalagriculture_version},)"
        ordering="NONE"
        side="BOTH"
