modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
    issueTrackerURL="https://github.com/BlakeBr0/MysticalAgriculture/issues"
    modId="mysticalcustomization"
    version="${mod_version}"
    displayName="Mystical Customization"
    updateJSONURL="https://api.blakesmods.com/v2/mods/mysticalcustomization/1.21/updates"
    displayURL="https://blakesmods.com/mystical-customization"
    # logoFile="examplemod.png"
    credits=""
    authors="BlakeBr0"
    description='''
    Allows modpack creators to add new content and modify existing content in Mystical Agriculture.
    '''

    [[dependencies.mysticalcustomization]]
        modId="neoforge"
        mandatory=true
        versionRange="[21.0.0-beta,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.mysticalcustomization]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.21,1.21.1)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.mysticalcustomization]]
        modId="cucumber"
        mandatory=true
        versionRange="[8.0.0,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.mysticalcustomization]]
        modId="mysticalagriculture"
        mandatory=true
        versionRange="[8.0.2,)"
        ordering="NONE"
        side="BOTH"
